import random 

R_EATING = "I don't like eating anything because I'm a bot obviously!"
R_ADVICE = "If I were you, I would go to the internet and type exactly what you wrote there!"
R_QUES_A = "Education is the medium that gives us the skills, techniques, information and knowledge to know, understand and respect the duties we have towards our society, families and nation."
R_QUES_B = "In India, the formal education system consists of five years of primary schooling, followed by three years of middle school and two years of high school. After the completion of high school, students can pursue higher education at a university or college."
R_QUES_C = "There will be no discernible divide between the arts, sciences, academic, vocational, curricular, and extracurricular disciplines. Foundational Reading and Numeracy will be prioritised. The 10+2 structure is replaced by a 5+3+3+4 model."
R_QUES_D = "The Western educational system in India is based on the idea that students should attend a brick-and-mortar school where they learn within a traditional setting. This system has been in place for hundreds of years and is modelled after the European university system."
R_QUES_E = "The Indian education system was based on rote learning. It focuses more on knowledge rather than experience. However, the western education system focuses on more practical-based learning. A student studying through the Indian education system gain knowledge about everything."
R_QUES_F = "India literacy rate for 2018 was 74.37%, a 5.07% increase from 2011. India literacy rate for 2011 was 69.30%, a 6.55% increase from 2006. India literacy rate for 2006 was 62.75%, a 1.74% increase from 2001. India literacy rate for 2001 was 61.01%, a 12.79% increase from 1991."
R_QUES_G = "India still has lower levels of literacy than many other nations, though. The literacy rate is 77.70%, with literate males at 84.70% and literate females at 70.30%, according to the National Family Health Survey (NFHS-5) and National Statistical Office: NSO (2021 and 2022)."
R_QUES_H = "There are two types of education in India: formal and informal. Formal education is imparted in schools, colleges, and universities that follow a set curriculum. Informal education is provided outside the formal education system and does not follow any set curriculum."
R_QUES_I = "Students who attend institutions of higher education obtain a wide range of personal, financial, and other lifelong benefits; likewise, taxpayers and society as a whole derive a multitude of direct and indirect benefits when citizens have access to postsecondary education. Accordingly, uneven rates of participation in higher education across different segments of US society should be a matter of urgent concern not only to the individuals directly affected, but also to public policymakers at the federal, state, and local levels. So you should study."
R_QUES_J = "Get organised. \n Don\'t skip class! \n Take notes. \n Talk to your teacher & ask questions. \n Space out your studying. \n Create a study plan – & stick to it. \n Don't just re-read but study. \n Set up a quiet study space."
R_QUES_K = "Education helps a person to get knowledge and improve confidence in life. It can help you improve your career and your personal growth. An educated person can become a great citizen in society. It helps you to take the right decisions in life."
R_QUES_L = "Education helps a person to get knowledge and improve confidence in life. It can help you improve your career and your personal growth. An educated person can become a great citizen in society."
R_QUES_M = "Special Schools \n This is a programme of the Ministry of Social Justice and Empowerment. Children with severe multiple disabilities who have difficulty in coping with regular schools are referred to such special schools. Most of these special schools are located in urban areas and run by voluntary organizations."
R_QUES_N = "When it comes to online classes, teachers can easily educate their students via virtual classrooms. Students can easily access learning materials from anywhere as long as they have proper access to an internet connection. Online classes provide teachers with a number of online learning tools including videos, audio, animations, virtual whiteboards, virtual conference rooms and live chats with the students. \n  On the other hand, offline classes provide students with a practical learning environment within the walls of a physical classroom. It allows students to closely interact with their teachers as well as participate actively in live discussions and debates. Students can also participate in recreational activities like art and physical education which contributes to the overall mental and physical development of the student. "
R_QUES_O = "With the emergence of technology, the method of delivering education has forever changed. As a matter of fact, online education has become a flexible instructional method of teaching wherein students can easily gain access to study material in the comfort of their homes. Moreover, online education provides an excellent opportunity for students who are unable to enrol in traditional classrooms as well as supports students in setting their own pace for studying. "
R_QUES_P = "Offline education is the traditional counterpart to online education and the original method of learning that allows students to have regular face-to-face interactions with their peers and teachers. As much as online education is predicted to be the future of learning, it cannot replace the holistic aspect of offline education."
R_QUES_Q = "Rural communities can benefit from Education by having more productive workers, increasing their overall income. Education boosts a person's ability to lead a group of people successfully and effectively since it gives them more information, confidence, skills, and experience."
R_QUES_R = "I think moral because ethics/values are really significant because they help us in developing and guiding our beliefs, attitudes, and behavior in a good manner. A good life is all made up of values. What type of person you are depends on what values you have acquired. According to me, a person learnt the values according to his surrounding."
R_QUES_S = "Moral Education is a subject that helps the teachers in helping the students in learning the value and virtues that would make them a good human being in a longer run. These virtues and values are important for the students as it helps them in being a better person for their entire life."
R_QUES_T = "Academic is used to describe things that relate to the work done in schools, colleges, and universities, especially work which involves studying and reasoning rather than practical or technical skills."
R_QUES_U = "A person who is educated becomes a good citizen of his country. Education is a crucial aspect of personal and professional development. It allows individuals to acquire the knowledge and skills necessary to succeed in their chosen field, and it can also provide opportunities for personal growth and fulfilment."
R_QUES_V = "Education for self-reliance is the development of individuals according to their needs and the demands of their primary society, and education is the development of the knowledge, skills and characters of students."
R_QUES_W = "Knowledge is the facts and information that you can recall or use. Education is how we acquire knowledge. Education grows with age. You learn new things every day, and those new things become part of your education"
R_QUES_X = "Education Minister Dharmendra Pradhan and External Affairs Minister Dr. S. Jai Shankar launched the Study in India (SII) Portal, SII Portal is a one-stop platform that will simplify the educational journey of international students in India."
R_QUES_Y = "Ministry of Education launched a Yuva Sangam Registration Portal in New Delhi. The Yuva Sangam program will work to connect the youth of the Northeast with the entire country. Under the program, 1000 youths in the age group of 18 to 30 will be sent to youth transformation programs in Bhutia and other states of the country."
R_QUES_Z = " Online learning structures vary, but generally, they’re designed to be more flexible than in-person classes, which means you can access your program on your own time and, more often than not, work at your own pace. "
R_QUES_AA = "Duolingo: a language learning app that offers courses in over 30 languages. \n Grammarly: a writing assistant that helps you write clear, mistake-free text."



def unknown():
    response = ["Could you please re-phrase that? ",
                "...",
                "Sounds about right.",
                "What does that mean?",
                "Sorry!"][
        random.randrange(5)]
    return response
